import type {
  BuyOptionResponse,
  OperationsTicker,
  OptionPicksResponse,
} from "../types";

export const MOCK_OPERATIONS_TICKERS: OperationsTicker[] = [
  {
    symbol: "NFLX",
    name: "Netflix Inc.",
    isFavorite: true,
    active: true,
    isOperationEnable: true,
    optimalRange: { low: 40, high: 80 },
    optimalRangeMinMax: { low: 35, high: 85 },
    optimalRangeAsOf: "2026-05-19",
    position: null,
  },
  {
    symbol: "TSLA",
    name: "Tesla Inc.",
    isFavorite: false,
    active: true,
    isOperationEnable: true,
    optimalRange: { low: 200, high: 280 },
    optimalRangeMinMax: null,
    optimalRangeAsOf: "2026-05-19",
    position: {
      symbol: "TSLA",
      status: "bought",
      contractType: "CALL",
      optionSymbol: "TSLA  260711C00250000",
      strike: 250,
      expiration: "2026-07-11",
      quantity: 1,
      orderId: "mock-1",
      orderStatus: "FILLED",
      tradePrice: 4.2,
      boughtAt: "2026-07-10T14:00:00Z",
      canBuy: false,
      canSell: true,
    },
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    isFavorite: false,
    active: true,
    isOperationEnable: true,
    optimalRange: null,
    optimalRangeMinMax: null,
    optimalRangeAsOf: null,
    position: null,
  },
];

export const MOCK_OPTION_PICKS: OptionPicksResponse = {
  contractType: "CALL",
  evaluatedAt: "2026-07-10T18:00:00Z",
  results: [
    {
      symbol: "NFLX",
      optimalRange: { low: 40, high: 80 },
      underlyingPrice: 73.4,
      expiration: "2026-07-11",
      dte: 1,
      pick: {
        optionSymbol: "NFLX  260711C00075000",
        strike: 75,
        bid: 1.0,
        ask: 1.1,
        mark: 1.05,
        delta: 0.42,
        expiration: "2026-07-11",
        dte: 1,
        putCall: "CALL",
      },
      status: "ok",
      message: null,
    },
    {
      symbol: "TSLA",
      optimalRange: { low: 200, high: 280 },
      underlyingPrice: 248.2,
      expiration: "2026-07-11",
      dte: 1,
      pick: {
        optionSymbol: "TSLA  260711C00250000",
        strike: 250,
        bid: 3.9,
        ask: 4.1,
        mark: 4.0,
        delta: 0.48,
        expiration: "2026-07-11",
        dte: 1,
        putCall: "CALL",
      },
      status: "ok",
      message: null,
    },
  ],
};

export const MOCK_BUY_RESPONSE: BuyOptionResponse = {
  symbol: "NFLX",
  contractType: "CALL",
  optionSymbol: "NFLX  260711C00075000",
  quantity: 1,
  strike: 75,
  expiration: "2026-07-11",
  orderId: "mock-order",
  orderStatus: "FILLED",
  tradePrice: 1.05,
  filledQuantity: 1,
  status: "bought",
  message: null,
  canBuy: false,
  canSell: true,
  position: {
    symbol: "NFLX",
    status: "bought",
    contractType: "CALL",
    optionSymbol: "NFLX  260711C00075000",
    strike: 75,
    expiration: "2026-07-11",
    quantity: 1,
    orderId: "mock-order",
    orderStatus: "FILLED",
    tradePrice: 1.05,
    boughtAt: "2026-07-10T18:01:00Z",
    canBuy: false,
    canSell: true,
  },
};
