import type { PreselectionResultResponse } from "../types";

export const MOCK_SETUP_SCAN_RESULT: PreselectionResultResponse = {
  runId: "presel-mock-001",
  status: "complete",
  message: "Mock Tickers SemiFinal complete.",
  simulationTimeEt: "2026-07-02T16:00:00-04:00",
  tradeDate: "2026-07-02",
  evaluatedAt: new Date().toISOString(),
  minScore: 0,
  candles: {
    referenceThroughEt: "2026-07-02T16:00:00-04:00",
    tradeDate: "2026-07-02",
    symbolsTotal: 5,
    symbolsStale: 2,
    symbolsRefreshed: 2,
    skippedRefresh: false,
    refreshedSymbols: ["AAPL", "MSFT"],
    failed: [],
  },
  summary: { symbolsTotal: 5, symbolsReady: 5, strategyCount: 1 },
  strategies: [
    {
      strategyId: "estrategia-05",
      name: "Inside Bollinger 15M",
      shortName: "Inside BB 15M",
      profileId: "inside-bb-15m-v1",
      tickerCount: 3,
      tickers: [
        {
          symbol: "AAPL",
          name: "Apple Inc.",
          currentlyActive: true,
          ready: true,
          score: 18,
          maxScore: 23,
          tier: "excellent",
          directionBias: "CALL",
          reasons: ["+3 h1BbExpand: 1h BB expanding.", "+2 dailyMa2040Align: Daily MA stack bullish."],
          avoidReasons: [],
          breakdown: [
            { key: "h1BbExpand", met: true, points: 3, maxPoints: 3, label: "1h BB expanding." },
            { key: "dailyMa2040Align", met: true, points: 2, maxPoints: 2, label: "Daily MA stack bullish." },
          ],
        },
        {
          symbol: "MSFT",
          name: "Microsoft Corp.",
          currentlyActive: false,
          ready: true,
          score: 14,
          maxScore: 23,
          tier: "strong",
          directionBias: "CALL",
          reasons: ["+2 h1CloseVsMa20: Close above MA20."],
          avoidReasons: ["adxBelow15: ADX 12.3."],
          breakdown: [],
        },
        {
          symbol: "TSLA",
          name: "Tesla Inc.",
          currentlyActive: false,
          ready: true,
          score: 8,
          maxScore: 23,
          tier: "skip",
          directionBias: "PUT",
          reasons: [],
          avoidReasons: ["dailyNeutral: Daily trend lateral."],
          breakdown: [],
        },
      ],
    },
  ],
};
