import type { GapForecastResult, PreselectionResultResponse } from "../types";

export const MOCK_GAP_FORECAST: GapForecastResult = {
  runId: "gap-mock-001",
  status: "complete",
  asOfEt: "2026-07-02T15:25:00-04:00",
  tradeDate: "2026-07-02",
  evaluatedAt: new Date().toISOString(),
  eligibleSymbols: ["AAPL", "INTC"],
  firstHighSymbols: ["AAPL", "INTC"],
  eligibleCount: 2,
  summary: {
    symbolsTotal: 3,
    symbolsReady: 3,
    eligibleCount: 2,
    counts: {
      gap_up_high: 1,
      gap_up_moderate: 1,
      no_edge: 0,
      gap_down_moderate: 0,
      gap_down_high: 1,
    },
  },
  tickers: [
    {
      symbol: "AAPL",
      name: "Apple Inc.",
      ready: true,
      score: 7,
      bias: "gap_up_high",
      label: "Gap Up probability = HIGH",
      close: 214.5,
      reasons: ["+2 rangeLocation: Close in top 20% of day."],
    },
    {
      symbol: "MSFT",
      name: "Microsoft Corp.",
      ready: true,
      score: 3,
      bias: "gap_up_moderate",
      label: "Gap Up bias = MODERATE",
      close: 450.2,
      reasons: [],
    },
    {
      symbol: "INTC",
      name: "Intel Corp.",
      ready: true,
      score: -6,
      bias: "gap_down_high",
      label: "Gap Down probability = HIGH",
      close: 32.1,
      reasons: [],
    },
  ],
  gapUpHigh: [
    {
      symbol: "AAPL",
      name: "Apple Inc.",
      ready: true,
      score: 7,
      bias: "gap_up_high",
      label: "Gap Up probability = HIGH",
      close: 214.5,
    },
  ],
  gapUpModerate: [
    {
      symbol: "MSFT",
      name: "Microsoft Corp.",
      ready: true,
      score: 3,
      bias: "gap_up_moderate",
      label: "Gap Up bias = MODERATE",
      close: 450.2,
    },
  ],
  noEdge: [],
  gapDownModerate: [],
  gapDownHigh: [
    {
      symbol: "INTC",
      name: "Intel Corp.",
      ready: true,
      score: -6,
      bias: "gap_down_high",
      label: "Gap Down probability = HIGH",
      close: 32.1,
    },
  ],
};

export const MOCK_SETUP_SCAN_RESULT: PreselectionResultResponse = {
  runId: "presel-mock-001",
  status: "complete",
  message: "Mock Tickers SemiFinal complete.",
  simulationTimeEt: "2026-07-02T16:00:00-04:00",
  tradeDate: "2026-07-02",
  evaluatedAt: new Date().toISOString(),
  minScore: 0,
  candles: {
    referenceThroughEt: "2026-07-02T16:00:00-04:00",
    tradeDate: "2026-07-02",
    symbolsTotal: 5,
    symbolsStale: 2,
    symbolsRefreshed: 2,
    skippedRefresh: false,
    refreshedSymbols: ["AAPL", "MSFT"],
    failed: [],
  },
  summary: { symbolsTotal: 5, symbolsReady: 5, strategyCount: 2 },
  gapForecast: MOCK_GAP_FORECAST,
  strategies: [
    {
      strategyId: "estrategia-05",
      name: "Inside Bollinger 15M",
      shortName: "Inside BB 15M",
      profileId: "inside-bb-15m-v1",
      candidateRuleKeys: ["open_inside_bb_15m"],
      tickerCount: 2,
      tickers: [
        {
          symbol: "AAPL",
          name: "Apple Inc.",
          currentlyActive: true,
          ready: true,
          score: 5,
          maxScore: 5,
          tier: "strong",
          directionBias: "CALL",
          reasons: [],
          avoidReasons: [],
          breakdown: [],
          candidateRules: [
            {
              ruleKey: "open_inside_bb_15m",
              met: true,
              status: "met",
              label: "Open inside BB 15m",
            },
          ],
          requiredPassed: true,
        },
        {
          symbol: "MSFT",
          name: "Microsoft Corp.",
          currentlyActive: false,
          ready: true,
          score: 5,
          maxScore: 5,
          tier: "strong",
          directionBias: "PUT",
          reasons: [],
          avoidReasons: [],
          breakdown: [],
          candidateRules: [
            {
              ruleKey: "open_inside_bb_15m",
              met: true,
              status: "met",
              label: "Open inside BB 15m",
            },
          ],
          requiredPassed: true,
        },
      ],
    },
    {
      strategyId: "panorama-completo",
      name: "Panorama completo",
      shortName: "Panorama",
      profileId: "panorama-completo-v1",
      tickerCount: 2,
      tickers: [
        {
          symbol: "AAPL",
          name: "Apple Inc.",
          currentlyActive: true,
          ready: true,
          score: 18,
          maxScore: 40,
          tier: "strong",
          directionBias: "CALL",
          reasons: ["+3 h1BbExpand: 1h BB expanding.", "+2 dailyMa2040Align: Daily MA stack bullish."],
          avoidReasons: [],
          breakdown: [
            { key: "h1BbExpand", met: true, points: 3, maxPoints: 3, label: "1h BB expanding." },
            { key: "dailyMa2040Align", met: true, points: 2, maxPoints: 2, label: "Daily MA stack bullish." },
          ],
          requiredPassed: true,
        },
        {
          symbol: "TSLA",
          name: "Tesla Inc.",
          currentlyActive: false,
          ready: true,
          score: 14,
          maxScore: 40,
          tier: "moderate",
          directionBias: "PUT",
          reasons: [],
          avoidReasons: ["dailyNeutral: Daily trend lateral."],
          breakdown: [],
          requiredPassed: true,
        },
      ],
    },
  ],
};
